name: PHP Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - uses: php-actions/phpunit@v3

    - name: PHPUnit tests 8.0
      uses: php-actions/phpunit@v3
      with:
        configuration: phpunit.xml
        php_version: "8.0"

    - name: PHPUnit tests 8.1
      uses: php-actions/phpunit@v3
      with:
        configuration: phpunit.xml
        php_version: "8.1"
